---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: debian-8.6
    driver:
        network:
            - ["private_network", {ip: "192.168.33.7"}]


suites:
  - name: default
    run_list:
        - recipe[django::default]
    attributes:
